### ISSUE TITLE
Travis CI config for Ionic 2 (iOS only)

### ISSUE THREAD

**Issue by minibhati93** [minibhati93/weather-ionic2#1]
Edit the existing `.travis.yml` to change the _build error_ flag to _build passing_

**Comment by dumptyd** [comment]
It should work after removing the `-g` flag from this line
https://github.com/minibhati93/weather-ionic2/blob/e346ccee4f85498143169bfc9a00da58a39a34a2/.travis.yml#L16

**Comment by minibhati93** [comment]
Hi @dumptyd . Thanks for your help. However, the issue still persists. Is there anything else that I can try ?

**Comment by dumptyd** [comment]
You only have to remove the `-g` flag from `npm install -g gulp` . You removed the flag from `npm` and `bower` too.
